Service Page  Section
AbhiPatel10/AISKCON-CONSTRUCTION pull request #41
Opened 2023-04-06 09:49 UTC by rolikaagarwal

CLOSES #24 

Full Screen- 

![image](https://user-images.githubusercontent.com/81984963/230340559-99cd9e2b-b347-4767-b913-bc196ba8b031.png)

Screen Size Reduced- 

![image](https://user-images.githubusercontent.com/81984963/230340995-2f999b48-4bc4-45ff-96d1-aa6727ca08d5.png)

Mobile Screen- 

![image](https://user-images.githubusercontent.com/81984963/230341423-df1a5ab2-3125-4529-91b9-d998a5f4bfb2.png)

2023-04-06 17:45 UTC, AbhiPatel10 commented
Make a separate service Page

2023-04-08 17:33 UTC, AbhiPatel10 commented
@rolikaagarwal Are you working on it?

2023-04-09 02:15 UTC, rolikaagarwal commented
Yes I'm working

2023-04-09 08:01 UTC, AbhiPatel10 requested changes

2023-04-09 08:01 UTC, AbhiPatel10 commented on ServiceSection/style.css
> +     margin-bottom: 20px;
margin: 20px 0px;

2023-04-09 11:55 UTC, rolikaagarwal commented
Changes Fixed.

2023-04-10 15:12 UTC, merged