Copyright year made dynamic in all the pages
AbhiPatel10/AISKCON-CONSTRUCTION pull request #67
Opened 2023-04-11 14:18 UTC by techRajat

closes #66

2023-04-13 05:08 UTC, AbhiPatel10 requested changes

2023-04-13 05:08 UTC, AbhiPatel10 commented on js/main.js
> +}
Give "/" in href

2023-04-15 18:44 UTC, AbhiPatel10 commented
@techrajat Solve requested changes

2023-04-16 09:35 UTC, techrajat commented
> @techrajat Solve requested changes

Done

2023-04-16 09:35 UTC, techrajat commented
> > @techrajat Solve requested changes
> 
> @AbhiPatel10  Done

2023-04-17 16:42 UTC, merged